name: goreleaser
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check GORELEASER_TOKEN
        run: |
          if [ -z "${GORELEASER_TOKEN}" ]; then
            echo "GORELEASER_TOKEN is not set."
            exit 1
          else
            echo "GORELEASER_TOKEN is set."
          fi
        env:
          GORELEASER_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '2.12.0'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}  # we use a custom token here
